version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
    - "KAFKA_CREATE_TOPICS=test:1:1"
    - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
    - "KAFKA_ADVERTISED_HOST_NAME=kafka"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zookeeper
  kafkarest:
    image: confluentinc/cp-kafka-rest
    environment:
    - "KAFKA_REST_HOST_NAME=kafkarest"
    - "KAFKA_REST_LISTENERS=http://kafkarest:8082"
    - "KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181"
    depends_on:
    - kafka
    - zookeeper
  kafkaui:
    image: landoop/kafka-topics-ui
    ports:
    - "8005:8000"
    environment:
    - "KAFKA_REST_PROXY_URL=kafkarest:8082"
    - "PROXY=true"
    depends_on:
    - kafka
    - zookeeper
